// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: snellgoapi.proto

#include "snellgoapi.pb.h"
#include "snellgoapi.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace snell {
namespace api {

static const char* SnellService_method_names[] = {
  "/snell.api.SnellService/QueryStats",
};

std::unique_ptr< SnellService::Stub> SnellService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SnellService::Stub> stub(new SnellService::Stub(channel));
  return stub;
}

SnellService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_QueryStats_(SnellService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SnellService::Stub::QueryStats(::grpc::ClientContext* context, const ::snell::api::StatsRequest& request, ::snell::api::StatsReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_QueryStats_, context, request, response);
}

void SnellService::Stub::experimental_async::QueryStats(::grpc::ClientContext* context, const ::snell::api::StatsRequest* request, ::snell::api::StatsReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_QueryStats_, context, request, response, std::move(f));
}

void SnellService::Stub::experimental_async::QueryStats(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::snell::api::StatsReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_QueryStats_, context, request, response, std::move(f));
}

void SnellService::Stub::experimental_async::QueryStats(::grpc::ClientContext* context, const ::snell::api::StatsRequest* request, ::snell::api::StatsReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_QueryStats_, context, request, response, reactor);
}

void SnellService::Stub::experimental_async::QueryStats(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::snell::api::StatsReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_QueryStats_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::snell::api::StatsReply>* SnellService::Stub::AsyncQueryStatsRaw(::grpc::ClientContext* context, const ::snell::api::StatsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::snell::api::StatsReply>::Create(channel_.get(), cq, rpcmethod_QueryStats_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::snell::api::StatsReply>* SnellService::Stub::PrepareAsyncQueryStatsRaw(::grpc::ClientContext* context, const ::snell::api::StatsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::snell::api::StatsReply>::Create(channel_.get(), cq, rpcmethod_QueryStats_, context, request, false);
}

SnellService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SnellService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SnellService::Service, ::snell::api::StatsRequest, ::snell::api::StatsReply>(
          [](SnellService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::snell::api::StatsRequest* req,
             ::snell::api::StatsReply* resp) {
               return service->QueryStats(ctx, req, resp);
             }, this)));
}

SnellService::Service::~Service() {
}

::grpc::Status SnellService::Service::QueryStats(::grpc::ServerContext* context, const ::snell::api::StatsRequest* request, ::snell::api::StatsReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace snell
}  // namespace api

