// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ssgoapi.proto

#include "ssgoapi.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace shadowsocks {
namespace api {
class StatsRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<StatsRequest> _instance;
} _StatsRequest_default_instance_;
class StatsReplyDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<StatsReply> _instance;
} _StatsReply_default_instance_;
}  // namespace api
}  // namespace shadowsocks
static void InitDefaultsscc_info_StatsReply_ssgoapi_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::shadowsocks::api::_StatsReply_default_instance_;
    new (ptr) ::shadowsocks::api::StatsReply();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::shadowsocks::api::StatsReply::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_StatsReply_ssgoapi_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_StatsReply_ssgoapi_2eproto}, {}};

static void InitDefaultsscc_info_StatsRequest_ssgoapi_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::shadowsocks::api::_StatsRequest_default_instance_;
    new (ptr) ::shadowsocks::api::StatsRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::shadowsocks::api::StatsRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_StatsRequest_ssgoapi_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_StatsRequest_ssgoapi_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_ssgoapi_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_ssgoapi_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_ssgoapi_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_ssgoapi_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::shadowsocks::api::StatsRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::shadowsocks::api::StatsRequest, password_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::shadowsocks::api::StatsReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::shadowsocks::api::StatsReply, upload_traffic_),
  PROTOBUF_FIELD_OFFSET(::shadowsocks::api::StatsReply, download_traffic_),
  PROTOBUF_FIELD_OFFSET(::shadowsocks::api::StatsReply, upload_speed_),
  PROTOBUF_FIELD_OFFSET(::shadowsocks::api::StatsReply, download_speed_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::shadowsocks::api::StatsRequest)},
  { 6, -1, sizeof(::shadowsocks::api::StatsReply)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::shadowsocks::api::_StatsRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::shadowsocks::api::_StatsReply_default_instance_),
};

const char descriptor_table_protodef_ssgoapi_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rssgoapi.proto\022\017shadowsocks.api\" \n\014Stat"
  "sRequest\022\020\n\010password\030\001 \001(\t\"l\n\nStatsReply"
  "\022\026\n\016upload_traffic\030\001 \001(\004\022\030\n\020download_tra"
  "ffic\030\002 \001(\004\022\024\n\014upload_speed\030\003 \001(\004\022\026\n\016down"
  "load_speed\030\004 \001(\0042W\n\tSSService\022J\n\nQuerySt"
  "ats\022\035.shadowsocks.api.StatsRequest\032\033.sha"
  "dowsocks.api.StatsReply\"\000B\tZ\007.;ssapib\006pr"
  "oto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_ssgoapi_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_ssgoapi_2eproto_sccs[2] = {
  &scc_info_StatsReply_ssgoapi_2eproto.base,
  &scc_info_StatsRequest_ssgoapi_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_ssgoapi_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ssgoapi_2eproto = {
  false, false, descriptor_table_protodef_ssgoapi_2eproto, "ssgoapi.proto", 284,
  &descriptor_table_ssgoapi_2eproto_once, descriptor_table_ssgoapi_2eproto_sccs, descriptor_table_ssgoapi_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_ssgoapi_2eproto::offsets,
  file_level_metadata_ssgoapi_2eproto, 2, file_level_enum_descriptors_ssgoapi_2eproto, file_level_service_descriptors_ssgoapi_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_ssgoapi_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_ssgoapi_2eproto)), true);
namespace shadowsocks {
namespace api {

// ===================================================================

void StatsRequest::InitAsDefaultInstance() {
}
class StatsRequest::_Internal {
 public:
};

StatsRequest::StatsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:shadowsocks.api.StatsRequest)
}
StatsRequest::StatsRequest(const StatsRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  password_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_password().empty()) {
    password_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_password(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:shadowsocks.api.StatsRequest)
}

void StatsRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_StatsRequest_ssgoapi_2eproto.base);
  password_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

StatsRequest::~StatsRequest() {
  // @@protoc_insertion_point(destructor:shadowsocks.api.StatsRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void StatsRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  password_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void StatsRequest::ArenaDtor(void* object) {
  StatsRequest* _this = reinterpret_cast< StatsRequest* >(object);
  (void)_this;
}
void StatsRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void StatsRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const StatsRequest& StatsRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_StatsRequest_ssgoapi_2eproto.base);
  return *internal_default_instance();
}


void StatsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:shadowsocks.api.StatsRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  password_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StatsRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string password = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_password();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "shadowsocks.api.StatsRequest.password"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* StatsRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:shadowsocks.api.StatsRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string password = 1;
  if (this->password().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_password().data(), static_cast<int>(this->_internal_password().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "shadowsocks.api.StatsRequest.password");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_password(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:shadowsocks.api.StatsRequest)
  return target;
}

size_t StatsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:shadowsocks.api.StatsRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string password = 1;
  if (this->password().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_password());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StatsRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:shadowsocks.api.StatsRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const StatsRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<StatsRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:shadowsocks.api.StatsRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:shadowsocks.api.StatsRequest)
    MergeFrom(*source);
  }
}

void StatsRequest::MergeFrom(const StatsRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:shadowsocks.api.StatsRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.password().size() > 0) {
    _internal_set_password(from._internal_password());
  }
}

void StatsRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:shadowsocks.api.StatsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StatsRequest::CopyFrom(const StatsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:shadowsocks.api.StatsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StatsRequest::IsInitialized() const {
  return true;
}

void StatsRequest::InternalSwap(StatsRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  password_.Swap(&other->password_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata StatsRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void StatsReply::InitAsDefaultInstance() {
}
class StatsReply::_Internal {
 public:
};

StatsReply::StatsReply(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:shadowsocks.api.StatsReply)
}
StatsReply::StatsReply(const StatsReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&upload_traffic_, &from.upload_traffic_,
    static_cast<size_t>(reinterpret_cast<char*>(&download_speed_) -
    reinterpret_cast<char*>(&upload_traffic_)) + sizeof(download_speed_));
  // @@protoc_insertion_point(copy_constructor:shadowsocks.api.StatsReply)
}

void StatsReply::SharedCtor() {
  ::memset(&upload_traffic_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&download_speed_) -
      reinterpret_cast<char*>(&upload_traffic_)) + sizeof(download_speed_));
}

StatsReply::~StatsReply() {
  // @@protoc_insertion_point(destructor:shadowsocks.api.StatsReply)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void StatsReply::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void StatsReply::ArenaDtor(void* object) {
  StatsReply* _this = reinterpret_cast< StatsReply* >(object);
  (void)_this;
}
void StatsReply::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void StatsReply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const StatsReply& StatsReply::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_StatsReply_ssgoapi_2eproto.base);
  return *internal_default_instance();
}


void StatsReply::Clear() {
// @@protoc_insertion_point(message_clear_start:shadowsocks.api.StatsReply)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&upload_traffic_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&download_speed_) -
      reinterpret_cast<char*>(&upload_traffic_)) + sizeof(download_speed_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StatsReply::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint64 upload_traffic = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          upload_traffic_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 download_traffic = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          download_traffic_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 upload_speed = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          upload_speed_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 download_speed = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          download_speed_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* StatsReply::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:shadowsocks.api.StatsReply)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 upload_traffic = 1;
  if (this->upload_traffic() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_upload_traffic(), target);
  }

  // uint64 download_traffic = 2;
  if (this->download_traffic() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(2, this->_internal_download_traffic(), target);
  }

  // uint64 upload_speed = 3;
  if (this->upload_speed() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(3, this->_internal_upload_speed(), target);
  }

  // uint64 download_speed = 4;
  if (this->download_speed() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(4, this->_internal_download_speed(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:shadowsocks.api.StatsReply)
  return target;
}

size_t StatsReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:shadowsocks.api.StatsReply)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 upload_traffic = 1;
  if (this->upload_traffic() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_upload_traffic());
  }

  // uint64 download_traffic = 2;
  if (this->download_traffic() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_download_traffic());
  }

  // uint64 upload_speed = 3;
  if (this->upload_speed() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_upload_speed());
  }

  // uint64 download_speed = 4;
  if (this->download_speed() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_download_speed());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StatsReply::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:shadowsocks.api.StatsReply)
  GOOGLE_DCHECK_NE(&from, this);
  const StatsReply* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<StatsReply>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:shadowsocks.api.StatsReply)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:shadowsocks.api.StatsReply)
    MergeFrom(*source);
  }
}

void StatsReply::MergeFrom(const StatsReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:shadowsocks.api.StatsReply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.upload_traffic() != 0) {
    _internal_set_upload_traffic(from._internal_upload_traffic());
  }
  if (from.download_traffic() != 0) {
    _internal_set_download_traffic(from._internal_download_traffic());
  }
  if (from.upload_speed() != 0) {
    _internal_set_upload_speed(from._internal_upload_speed());
  }
  if (from.download_speed() != 0) {
    _internal_set_download_speed(from._internal_download_speed());
  }
}

void StatsReply::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:shadowsocks.api.StatsReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StatsReply::CopyFrom(const StatsReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:shadowsocks.api.StatsReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StatsReply::IsInitialized() const {
  return true;
}

void StatsReply::InternalSwap(StatsReply* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StatsReply, download_speed_)
      + sizeof(StatsReply::download_speed_)
      - PROTOBUF_FIELD_OFFSET(StatsReply, upload_traffic_)>(
          reinterpret_cast<char*>(&upload_traffic_),
          reinterpret_cast<char*>(&other->upload_traffic_));
}

::PROTOBUF_NAMESPACE_ID::Metadata StatsReply::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace shadowsocks
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::shadowsocks::api::StatsRequest* Arena::CreateMaybeMessage< ::shadowsocks::api::StatsRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::shadowsocks::api::StatsRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::shadowsocks::api::StatsReply* Arena::CreateMaybeMessage< ::shadowsocks::api::StatsReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::shadowsocks::api::StatsReply >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
