// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ssgoapi.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ssgoapi_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ssgoapi_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ssgoapi_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ssgoapi_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ssgoapi_2eproto;
namespace api {
class StatsReply;
class StatsReplyDefaultTypeInternal;
extern StatsReplyDefaultTypeInternal _StatsReply_default_instance_;
class StatsRequest;
class StatsRequestDefaultTypeInternal;
extern StatsRequestDefaultTypeInternal _StatsRequest_default_instance_;
}  // namespace api
PROTOBUF_NAMESPACE_OPEN
template<> ::api::StatsReply* Arena::CreateMaybeMessage<::api::StatsReply>(Arena*);
template<> ::api::StatsRequest* Arena::CreateMaybeMessage<::api::StatsRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace api {

// ===================================================================

class StatsRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:api.StatsRequest) */ {
 public:
  StatsRequest();
  virtual ~StatsRequest();

  StatsRequest(const StatsRequest& from);
  StatsRequest(StatsRequest&& from) noexcept
    : StatsRequest() {
    *this = ::std::move(from);
  }

  inline StatsRequest& operator=(const StatsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StatsRequest& operator=(StatsRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const StatsRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StatsRequest* internal_default_instance() {
    return reinterpret_cast<const StatsRequest*>(
               &_StatsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(StatsRequest& a, StatsRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StatsRequest* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StatsRequest* New() const final {
    return CreateMaybeMessage<StatsRequest>(nullptr);
  }

  StatsRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StatsRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const StatsRequest& from);
  void MergeFrom(const StatsRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StatsRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "api.StatsRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ssgoapi_2eproto);
    return ::descriptor_table_ssgoapi_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPasswordFieldNumber = 1,
  };
  // string password = 1;
  void clear_password();
  const std::string& password() const;
  void set_password(const std::string& value);
  void set_password(std::string&& value);
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  std::string* mutable_password();
  std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // @@protoc_insertion_point(class_scope:api.StatsRequest)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ssgoapi_2eproto;
};
// -------------------------------------------------------------------

class StatsReply :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:api.StatsReply) */ {
 public:
  StatsReply();
  virtual ~StatsReply();

  StatsReply(const StatsReply& from);
  StatsReply(StatsReply&& from) noexcept
    : StatsReply() {
    *this = ::std::move(from);
  }

  inline StatsReply& operator=(const StatsReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline StatsReply& operator=(StatsReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const StatsReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StatsReply* internal_default_instance() {
    return reinterpret_cast<const StatsReply*>(
               &_StatsReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(StatsReply& a, StatsReply& b) {
    a.Swap(&b);
  }
  inline void Swap(StatsReply* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StatsReply* New() const final {
    return CreateMaybeMessage<StatsReply>(nullptr);
  }

  StatsReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StatsReply>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const StatsReply& from);
  void MergeFrom(const StatsReply& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StatsReply* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "api.StatsReply";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ssgoapi_2eproto);
    return ::descriptor_table_ssgoapi_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUploadTrafficFieldNumber = 1,
    kDownloadTrafficFieldNumber = 2,
    kUploadSpeedFieldNumber = 3,
    kDownloadSpeedFieldNumber = 4,
  };
  // uint64 upload_traffic = 1;
  void clear_upload_traffic();
  ::PROTOBUF_NAMESPACE_ID::uint64 upload_traffic() const;
  void set_upload_traffic(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_upload_traffic() const;
  void _internal_set_upload_traffic(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 download_traffic = 2;
  void clear_download_traffic();
  ::PROTOBUF_NAMESPACE_ID::uint64 download_traffic() const;
  void set_download_traffic(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_download_traffic() const;
  void _internal_set_download_traffic(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 upload_speed = 3;
  void clear_upload_speed();
  ::PROTOBUF_NAMESPACE_ID::uint64 upload_speed() const;
  void set_upload_speed(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_upload_speed() const;
  void _internal_set_upload_speed(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 download_speed = 4;
  void clear_download_speed();
  ::PROTOBUF_NAMESPACE_ID::uint64 download_speed() const;
  void set_download_speed(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_download_speed() const;
  void _internal_set_download_speed(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:api.StatsReply)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint64 upload_traffic_;
  ::PROTOBUF_NAMESPACE_ID::uint64 download_traffic_;
  ::PROTOBUF_NAMESPACE_ID::uint64 upload_speed_;
  ::PROTOBUF_NAMESPACE_ID::uint64 download_speed_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ssgoapi_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StatsRequest

// string password = 1;
inline void StatsRequest::clear_password() {
  password_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& StatsRequest::password() const {
  // @@protoc_insertion_point(field_get:api.StatsRequest.password)
  return _internal_password();
}
inline void StatsRequest::set_password(const std::string& value) {
  _internal_set_password(value);
  // @@protoc_insertion_point(field_set:api.StatsRequest.password)
}
inline std::string* StatsRequest::mutable_password() {
  // @@protoc_insertion_point(field_mutable:api.StatsRequest.password)
  return _internal_mutable_password();
}
inline const std::string& StatsRequest::_internal_password() const {
  return password_.GetNoArena();
}
inline void StatsRequest::_internal_set_password(const std::string& value) {
  
  password_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void StatsRequest::set_password(std::string&& value) {
  
  password_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:api.StatsRequest.password)
}
inline void StatsRequest::set_password(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  password_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:api.StatsRequest.password)
}
inline void StatsRequest::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:api.StatsRequest.password)
}
inline std::string* StatsRequest::_internal_mutable_password() {
  
  return password_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* StatsRequest::release_password() {
  // @@protoc_insertion_point(field_release:api.StatsRequest.password)
  
  return password_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void StatsRequest::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:api.StatsRequest.password)
}

// -------------------------------------------------------------------

// StatsReply

// uint64 upload_traffic = 1;
inline void StatsReply::clear_upload_traffic() {
  upload_traffic_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 StatsReply::_internal_upload_traffic() const {
  return upload_traffic_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 StatsReply::upload_traffic() const {
  // @@protoc_insertion_point(field_get:api.StatsReply.upload_traffic)
  return _internal_upload_traffic();
}
inline void StatsReply::_internal_set_upload_traffic(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  upload_traffic_ = value;
}
inline void StatsReply::set_upload_traffic(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_upload_traffic(value);
  // @@protoc_insertion_point(field_set:api.StatsReply.upload_traffic)
}

// uint64 download_traffic = 2;
inline void StatsReply::clear_download_traffic() {
  download_traffic_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 StatsReply::_internal_download_traffic() const {
  return download_traffic_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 StatsReply::download_traffic() const {
  // @@protoc_insertion_point(field_get:api.StatsReply.download_traffic)
  return _internal_download_traffic();
}
inline void StatsReply::_internal_set_download_traffic(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  download_traffic_ = value;
}
inline void StatsReply::set_download_traffic(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_download_traffic(value);
  // @@protoc_insertion_point(field_set:api.StatsReply.download_traffic)
}

// uint64 upload_speed = 3;
inline void StatsReply::clear_upload_speed() {
  upload_speed_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 StatsReply::_internal_upload_speed() const {
  return upload_speed_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 StatsReply::upload_speed() const {
  // @@protoc_insertion_point(field_get:api.StatsReply.upload_speed)
  return _internal_upload_speed();
}
inline void StatsReply::_internal_set_upload_speed(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  upload_speed_ = value;
}
inline void StatsReply::set_upload_speed(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_upload_speed(value);
  // @@protoc_insertion_point(field_set:api.StatsReply.upload_speed)
}

// uint64 download_speed = 4;
inline void StatsReply::clear_download_speed() {
  download_speed_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 StatsReply::_internal_download_speed() const {
  return download_speed_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 StatsReply::download_speed() const {
  // @@protoc_insertion_point(field_get:api.StatsReply.download_speed)
  return _internal_download_speed();
}
inline void StatsReply::_internal_set_download_speed(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  download_speed_ = value;
}
inline void StatsReply::set_download_speed(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_download_speed(value);
  // @@protoc_insertion_point(field_set:api.StatsReply.download_speed)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace api

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ssgoapi_2eproto
